### ISSUE TITLE
Feature: 信息解析

### ISSUE THREAD

**Issue by chfwd** [ToolDelta/ToolDelta#131]
### 希望能解决的问题

在 956356d 中，ToolDelta引入了将标识符信息翻译为正常文本的功能。但是在这些标识符中，有一些是基岩版中所没有的（Java版中的）内容，而有一些基岩版中有的内容却没有被收录进去。
举个例子，
在`tooldelta/packets.py`第2148行中有这么一段：
```
"commands.datapack.list.enabled.success": "已启用%s个数据包：%s",
```
很显然，在基岩版中并不存在`/datapack`命令，也不存在数据包。
此外，有许多基岩版中的内容缺失了，比如`/damage`命令的相关文本。在基岩版语言文件中有这样一段：
```
commands.damage.description=对指定实体实施伤害。
```
而在`tooldelta/packets.py`中，却没有这一段。

### 描述所需要的功能

打开MC安装包，转到`/assets/resource_packs/vanilla/texts/`目录，打开`zh_CN.lang`文件，把这里的内容一一对应转成字典代替`tooldelta/packets.py`中的相关内容就可以了。
不过，为了再完美一点，可以再打开网易的安装包，转到`/assets/resource_packs/vanilla_netease/texts/`目录，把这里`zh_CN.lang`文件里的内容也一并加入。网易在这个文件里改善了原版部分不准确的翻译，也添加了一些网易版独有的文本，加入这些内容，可以更好地同步网易版。

**Comment by xingchentye** [comment]
好，我将会在下次提交时修改



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年3月2日(周六) 晚上11:01
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [ToolDelta/ToolDelta] Feature: 信息解析 (Issue #131)




 
希望能解决的问题
 
在 956356d 中，ToolDelta引入了将标识符信息翻译为正常文本的功能。但是在这些标识符中，有一些是基岩版中所没有的（Java版中的）内容，而有一些基岩版中有的内容却没有被收录进去。
 举个例子，
 在tooldelta/packets.py第2148行中有这么一段：
 "commands.datapack.list.enabled.success": "已启用%s个数据包：%s",  
很显然，在基岩版中并不存在/datapack命令，也不存在数据包。
 此外，有许多基岩版中的内容缺失了，比如/damage命令的相关文本。在基岩版语言文件中有这样一段：
 commands.damage.description=对指定实体实施伤害。  
而在tooldelta/packets.py中，却没有这一段。
 
描述所需要的功能
 
打开MC安装包，转到/assets/resource_packs/vanilla/texts/目录，打开zh_CN.lang文件，把这里的内容一一对应转成字典代替tooldelta/packets.py中的相关内容就可以了。
 不过，为了再完美一点，可以再打开网易的安装包，转到/assets/resource_packs/vanilla_netease/texts/目录，把这里zh_CN.lang文件里的内容也一并加入。网易在这个文件里改善了原版部分不准确的翻译，也添加了一些网易版独有的文本，加入这些内容，可以更好地同步网易版。

**Comment by xingchentye** [comment]
因为放在github后通过网络访问及其不稳定，可能导致程序运行出现停滞现象，所以我决定将其以.py文件的方式保存

**Comment by Happy2018new** [comment]
> 因为放在github后通过网络访问及其不稳定，可能导致程序运行出现停滞现象，所以我决定将其以.py文件的方式保存

为什么不能把文件直接打包进程序？

**Comment by SuperScript-PRC** [comment]
wow chfwd here

**Comment by chfwd** [comment]
> wow chfwd here

wow SuperScript here

**Comment by wling-art** [comment]
fix repo https://github.com/ToolDelta/ToolDelta-Game_Texts
fix commit https://github.com/ToolDelta/ToolDelta/commit/956356d4c1b2075855682a5c1a9190cb8a6231be

详细请看commit列表
