### ISSUE TITLE
Feature: 选择验证服务器

### ISSUE THREAD

**Issue by wling-art** [ToolDelta/ToolDelta#141]
### 希望能解决的问题

我们貌似可以在第一次配置的时候让用户选择在社区中的验证服务器

### 描述所需要的功能

在第一次配置td时加入选择验证服务器的步骤

我认为这是非常简单的，但是得看各位觉得这提议怎么样

**Comment by wling-art** [comment]
已知:
FB官方服务器api: https://api.fastbuilder.pro

咕咕酱 FB验证服务器: https://liliya233.uk

未知：
Edotcs FB验证服务器

**Comment by SuperScript-PRC** [comment]
Done
