### ISSUE TITLE
Bug: 优化启动速度

### ISSUE THREAD

**Issue by wling-art** [ToolDelta/ToolDelta#142]
### 操作系统

Windows

### ToolDelta 版本

0.4.2

### 描述问题

因为启动需要检测多个网址比如更新啥的可能会导致拖慢启动速度

### 复现步骤

打开td选择1模式

### 期望的结果

快速启动，而不是看网速启动

**Comment by SuperScript-PRC** [comment]
设置检测更新的时间间隔，例如 10min 一次

**Comment by SuperScript-PRC** [comment]
> 设置检测更新的时间间隔，例如 10min 一次

先启动ToolDelta，在运行过程中后台自动检测也是一个好办法

**Comment by xingchentye** [comment]
我已了解，大概将在明天晚上提交



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年3月10日(周日) 晚上10:16
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [ToolDelta/ToolDelta] Bug: 优化启动速度 (Issue #142)




 
操作系统
 
Windows
 
ToolDelta 版本
 
0.4.2
 
描述问题
 
因为启动需要检测多个网址比如更新啥的可能会导致拖慢启动速度
 
复现步骤
 
打开td选择1模式
 
期望的结果
 
快速启动，而不是看网速启动
 
截图或日志
 
No response

**Comment by xingchentye** [comment]
已解决!
