### ISSUE TITLE
Feature: 插件市场下载完插件自动加载插件

### ISSUE THREAD

**Issue by wling-art** [ToolDelta/ToolDelta#143]
### 希望能解决的问题

在插件市场还需要重新启动才能用新的插件

### 描述所需要的功能

插件市场下载完插件自动加载插件，如果本地已经有插件那个插件则判断为更新插件而不自动热加载且提示用户需要重启才能加载此插件

**Comment by SuperScript-PRC** [comment]
Done with new feature: [Commit 968](https://github.com/ToolDelta/ToolDelta/commit/0000bbc230eaa31959437c3d1f40b4602ba4d0a3)

**Comment by SuperScript-PRC** [comment]
WARNING: 当已加载同名插件的时候，不会提示热启动该插件。
所以，当同时下载了新版本的插件前置时，存在旧的前置插件，则前置插件不会更新，还是需要重启以完全更新插件。
