### ISSUE TITLE
Feature: 插件热重载

### ISSUE THREAD

**Issue by SuperScript-PRC** [ToolDelta/ToolDelta#144]
### 希望能解决的问题

不重启系统而直接热重载插件

### 描述所需要的功能

此功能在 `ToolDelta v1.0.1` 中曾被实现过， 但是由于插件可能新建了线程不能被正确地停止而无法安全重载插件。

**Comment by wling-art** [comment]
我觉得td应该一个公共值，如果获取到需要停止则通知这些线程，我认为这是插件作者需要去适配的
threading.Event()怎么样？

**Comment by xingchentye** [comment]
试过，但是这样需要在while的时候 not xxx



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年3月16日(周六) 凌晨1:51
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: Re: [ToolDelta/ToolDelta] Feature: 插件热重载 (Issue #144)




 
我觉得td应该一个公共值，如果获取到需要停止则通知这些线程，我认为这是插件作者需要去适配的
 threading.Event()怎么样？

**Comment by xingchentye** [comment]
> 试过，但是这样需要在while的时候 not xxx
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年3月16日(周六) 凌晨1:51 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: Re: [ToolDelta/ToolDelta] Feature: 插件热重载 (Issue #144) 我觉得td应该一个公共值，如果获取到需要停止则通知这些线程，我认为这是插件作者需要去适配的 threading.Event()怎么样？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

但是这应该是唯一的办法

**Comment by wling-art** [comment]
我认为可能貌似不需要这个热重载功能？大概只需要一个热加载就已经貌似很不错了。

**Comment by SuperScript-PRC** [comment]
嗯，确实..中止这个计划吧
