### ISSUE TITLE
Bug: 出现异常

### ISSUE THREAD

**Issue by wling-art** [ToolDelta/ToolDelta#147]
### 操作系统

Linux

### ToolDelta 版本

latest

### 描述问题

获取时堵塞主线程导致无法退出

### 复现步骤

1.启动

### 期望的结果

报错退出

### 截图或日志

![image](https://github.com/ToolDelta/ToolDelta/assets/90316914/bf023bd2-63f2-4750-b052-c13a8656a169)

**Comment by SuperScript-PRC** [comment]
GameText未能正常获取，确实需要修复，也可以试试重启

**Comment by wling-art** [comment]
主要是无法自己退出

**Comment by wling-art** [comment]
Fix https://github.com/ToolDelta/ToolDelta/commit/eecae53c9238b2d3b57c3874b881a47574e77b62
