### ISSUE TITLE
Bug: 插件注册之后不会再次更新注册表

### ISSUE THREAD

**Issue by chfwd** [ToolDelta/ToolDelta#150]
### 操作系统

Linux

### ToolDelta 版本

0.4.12

### 描述问题

插件在第一次被加载时，ToolDelta会在注册表内写入插件的信息供插件管理器使用。然而，再次加载这个插件时，加载器检测到这个插件已经被注册过了，就会直接跳过更新注册表的步骤，即使这个插件的信息已被更改过。([原代码](https://github.com/ToolDelta/ToolDelta/blob/main/tooldelta/plugin_load/classic_plugin/__init__.py#L135-L136))这也就造成了插件信息不同步的问题。

### 复现步骤

1.创建一个插件，版本为0.0.1
2.启动ToolDelta加载插件
3.发现注册表内插件版本为0.0.1
4.更新插件版本为0.0.2
5.启动ToolDelta加载插件
6.发现注册表内插件版本仍为0.0.1

### 期望的结果

修改插件注册表的注册逻辑：在插件信息被更改时，同步更改注册表内的信息；在插件不存在时，同步删除注册表内的信息。

**Comment by wling-art** [comment]
让我尝试修改它罢

**Comment by SuperScript-PRC** [comment]
尝试修复中...

**Comment by SuperScript-PRC** [comment]
已被修复，np

**Comment by wling-art** [comment]
fix https://github.com/ToolDelta/ToolDelta/commit/3f38733dcaf7a0c159cc91cc04da6156e0864f82

**Comment by SuperScript-PRC** [comment]
> fix [3f38733](https://github.com/ToolDelta/ToolDelta/commit/3f38733dcaf7a0c159cc91cc04da6156e0864f82)

此修复出现问题， 正在改正。

**Comment by SuperScript-PRC** [comment]
fix [(266064)](https://github.com/ToolDelta/ToolDelta/commit/3f38733dcaf7a0c159cc91cc04da6156e0864f82)

**Comment by SuperScript-PRC** [comment]
fix [266064a](https://github.com/ToolDelta/ToolDelta/commit/266064a)
