### ISSUE TITLE
建议优化仓库管理与GitHub Release自动生成

### ISSUE THREAD

**Issue by wling-art** [ToolDelta/ToolDelta#153]
### 问题描述

当前仓库的提交信息存在混乱的情况，缺乏明确的更改介绍，且一个功能更新往往包含多个提交，导致了提交历史的可读性和追溯性下降。

### 建议解决方案

为了改善这一问题，我建议引入 Pull Request（PR）流程，以便更好地管理功能更新并规范提交信息，并且利用 GitHub 的自动生成 Release 总结功能。具体建议如下：

1. **使用 Pull Request 进行功能更新：** 所有功能更新应当通过创建 PR 的方式进行。这样可以将相关的提交组织在一起，并且便于审查和讨论。

2. **简洁明了的 PR 简介：** 在创建 PR 时，提交者应当提供简洁明了的简介，清晰地说明此次 PR 的变更内容、影响范围以及可能的风险。这有助于审阅者快速理解 PR 的意图和影响。

3. **规范提交信息：** 提交信息应当遵循统一的格式和规范，包括但不限于描述更改的类型（新增功能、bug 修复、性能优化等）、更改的范围（模块、文件）、更改的详细描述等信息。

4. **保持单一功能原则（Single Responsibility Principle）：** 每个 PR 应当只包含一个独立的功能更新或修复。这有助于降低代码审阅的复杂度，并且便于跟踪和回溯功能变更历史。

5. **利用 GitHub Release Notes 功能：** GitHub 提供了自动生成 Release Notes 的功能，可以根据 PR 的内容自动汇总生成 Release 总结。通过规范 PR 的标题和简介，以及提交信息的格式，可以充分利用这一功能，减少手动编写 Release Notes 的工作量。

6. **灵活的配置选项：** GitHub 提供了丰富的配置选项，可以根据实际需求定制 Release Notes 的生成规则。我们可以配置筛选条件，包括标签、里程碑、提交信息关键词等，以满足不同情况下的 Release 总结需求。

7. **自动化流程：** 通过将 PR 流程与自动生成 Release Notes 集成，可以实现更高效的发布流程。只需在合并 PR 后，GitHub 就会自动根据配置生成相应的 Release 总结，无需手动干预，大大提升了发布效率。

### 预期效果

通过引入以上建议的 PR 流程，并规范提交信息的格式，我们可以达到以下效果：

- 提高提交历史的可读性和追溯性。
- 减少因为提交信息不清晰而导致的沟通成本。
- 提高团队协作效率，促进代码质量的提升。
- 更便捷地生成 GitHub Release 总结，减少手动编写 Release Notes 的工作量。

### 补充说明

本提议旨在改善当前仓库的提交管理情况，希望得到大家的支持和配合。欢迎就提议中的任何问题进行讨论，并提出进一步的改进建议。

### 相关参考

- [自动 GitHub Release 总结](https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes#configuration-options)

**Comment by Happy2018new** [comment]
仍然需要引起重视的，使用拉取请求不应该出现滥用的情况，这意味着短小精悍的问题修复不应该被变成拉取请求。

**Comment by SuperScript-PRC** [comment]
部分功能由于项目规模不是很大暂时不很需要（e.g.[PhoenixBuilder](https://github.com/LNSSPsd/PhoenixBuilder)），但是我并不会对目前的做法有什么异议。不过确实应该规范提交信息（fix bugs & file changed FORBIDDENED）。
另外，是否需要筛选可能由文档或大语言模型生成的建议中的冗余信息？看起来文档内容太宽泛了。

**Comment by wling-art** [comment]
> 部分功能由于项目规模不是很大暂时不很需要（e.g.[PhoenixBuilder](https://github.com/LNSSPsd/PhoenixBuilder)），但是我并不会对目前的做法有什么异议。不过确实应该规范提交信息（fix bugs & file changed FORBIDDENED）。 另外，是否需要筛选可能由文档或大语言模型生成的建议中的冗余信息？看起来文档内容太宽泛了。

这是没办法的，如果要上大模型需要gpu服务器，或者需要money
版本更改就是需要我们展示我们做了哪些更改
