### ISSUE TITLE
Bug: 修改密码时意外地修改错租赁服号

### ISSUE THREAD

**Issue by wangzm5573** [ToolDelta/ToolDelta#154]
### 操作系统

Windows

### ToolDelta 版本

newest

### 描述问题

![image](https://github.com/ToolDelta/ToolDelta/assets/121756620/15b22c18-05b4-441b-9ffb-09923678caee)

### 复现步骤

首先运行 ToolDelta,
然后 4-修改配置,
接着 2-修改密码,
最后发现租赁服号被改...

### 期望的结果

修改密码时应该正确地修改密码.
(qwq)
(Super~~~~~~~)

**Comment by wling-art** [comment]
关于你的复现步骤十分模糊，请重新详细说明
这对我们修改此bug十分有帮助，也能快速定位

**Comment by xingchentye** [comment]
我现在因为一些原因无法进行修改，你可以看看图片的内容，上面有错误的地方



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年5月3日(周五) 晚上11:04
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: Re: [ToolDelta/ToolDelta] Bug: 修改密码时意外地修改错租赁服号 (Issue #154)




 
关于你的复现步骤十分模糊，请重新详细说明
 这对我们修改此bug十分有帮助，也能快速定位
