### ISSUE TITLE
数据库功能建议

### ISSUE THREAD

**Issue by SuperScript-PRC** [ToolDelta/ToolDelta#181]
### 希望能解决的问题

在使用utils.py附带的数据库时，为什么需要加密数据库？鉴于这个项目是开源项目，是不是可以去掉此功能？

### 描述所需要的功能

移除数据库加解密功能

**Comment by xingchentye** [comment]
这个加密功能是可选的，可以选择不加密，另外我将要将其作为pypi库安装

**Comment by xingchentye** [comment]
> 这个加密功能是可选的，可以选择不加密，另外我将要将其作为pypi库安装

ToolDelta是开源的，不代表某些插件希望他的数据库内容被人所读取

**Comment by SuperScript-PRC** [comment]
> > 这个加密功能是可选的，可以选择不加密，另外我将要将其作为pypi库安装
> 
> ToolDelta是开源的，不代表某些插件希望他的数据库内容被人所读取

能自己设置秘钥啊，okay
