### ISSUE TITLE
Feature: 关于导入schem等Minecraft多方块结构的插件的实施办法

### ISSUE THREAD

**Issue by wling-art** [ToolDelta/ToolDelta#55]
待完善

**Comment by SuperScript-PRC** [comment]
标题有歧义容易误导其他人，已更改

**Comment by wling-art** [comment]
我认为我需要攻克读取文件这个问题，是否有相关库可以帮助我们？

**Comment by Happy2018new** [comment]
This feature should using C related codes, such as DLL, etc.

**Comment by SuperScript-PRC** [comment]
really not context deadline? who will reslove this problem?

**Comment by SuperScript-PRC** [comment]
> really not context deadline? who will resolve this problem?

translate this issue 2 plugin market object is wise

**Comment by Happy2018new** [comment]
> really not context deadline? who will resolve this problem?

I don't know. But I think we will not resolve this problem within 6 months.
But I think we could resolve this issue slowly, so delete `context deadline` maybe is a choice.

**Comment by xingchentye** [comment]
> 此功能应使用 C 相关功能，例如 DLL 等。

就在刚刚，我找到了一个最后更新在两年前，使用C语言的NBT解析库，测试目前为止可以正常使用
![image](https://github.com/user-attachments/assets/82927fdb-a9d6-4f1f-967b-e67ded92c269)

**Comment by xingchentye** [comment]
> > 此功能应使用 C 相关功能，例如 DLL 等。
> 
> 就在刚刚，我找到了一个最后更新在两年前，使用C语言的NBT解析库，测试目前为止可以正常使用 ![image](https://private-user-images.githubusercontent.com/123609288/350816988-82927fdb-a9d6-4f1f-967b-e67ded92c269.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2MTQ0NzYsIm5iZiI6MTcyMTYxNDE3NiwicGF0aCI6Ii8xMjM2MDkyODgvMzUwODE2OTg4LTgyOTI3ZmRiLWE5ZDYtNGYxZi05NjdiLWU2N2RlZDkyYzI2OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyMlQwMjA5MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zODBhZTQ3MjM3NDgzYTJiNzI3NDJlMDY5ODRlNmZkMjE1NmUwYTU1MDc4MTY4MTgyMjQyYzdiOWIxZjliNGZiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.H2gEc9w35FkFEdka49NUXqSFivCCfYBD_8W6RaySr90)

我需要尝试修改一下，以适配Python！
