### ISSUE TITLE
由于主分支仅`PR`的问题导致Actions无法顺利运行完成

### ISSUE THREAD

**Issue by SuperScript-PRC** [ToolDelta/ToolDelta#95]
Action fail log url:
https://github.com/ToolDelta/ToolDelta/actions/runs/8033731408/job/21944519888#step:6:84
需要及时进行更改以免以后的提交出现类似问题.

**Comment by wling-art** [comment]
fix https://github.com/ToolDelta/ToolDelta/pull/99

**Comment by Happy2018new** [comment]
- [ ]

**Comment by Happy2018new** [comment]
> 看起来 #99 的处理办法并不是很好，此问题仍需进一步讨论。

看起来造成的原因是提交被拒绝了，这恐怕是分支保护设置的有问题？
不过原有的实现实际上也不算多好，因为只要那个目录下有提交，就会提交一次 `JSON` 。
或许应该优化一下，看看新生成的 `JSON` 和原有的 `JSON` 是否一致，如果一致才提交，否则就不提交了？

**Comment by wling-art** [comment]
改为了只在push的时候刷新json，pr不进行生成

**Comment by wling-art** [comment]
fix https://github.com/ToolDelta/ToolDelta/commit/df1811f223d5b0160d0160f79406d396729b1edb
